Repository AY2425S1-CS2103T-T13-4/tp, pull requests merged in 2024-10, with the labels that each got.

#74 Update testutil for tests
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#82 Feature: Find Person
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/ponharish.md
  docs/team/suhayl13.md
  src/main/java/seedu/address/logic/commands/FindNricCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindNricCommandParser.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/NricContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindNricCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindNricCommandParserTest.java
Labels: type.Task

#116 Update delete command in user guide
  docs/UserGuide.md
  docs/images/deleteDavidResult.png
Labels: type.Task

#127 update Constructor of CommandResult class
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Enhancement, type.Task

#135 Find person UI
  docs/DeveloperGuide.md
  docs/team/ponharish.md
  src/main/java/seedu/address/ui/FindPersonCard.java
  src/main/java/seedu/address/ui/FindPersonPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FindPersonCard.fxml
  src/main/resources/view/FindPersonCardStyle.css
  src/main/resources/view/FindPersonList.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#162 Update cli syntax for edit appointment command
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditAppointmentParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
Labels: alpha-bug

#166 Find Appointment Command
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/criteria/AppointmentSearchCriteria.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/FindAppointmentCard.java
  src/main/java/seedu/address/ui/FindAppointmentPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FindAppointmentCard.fxml
  src/main/resources/view/FindAppointmentCardStyle.css
  src/main/resources/view/FindAppointmentList.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/FindAppointmentCommandParserTest.java
Labels: type.Task

#168 Update AppointmentSearchCriteria
  src/main/java/seedu/address/logic/parser/criteria/AppointmentSearchCriteria.java
Labels: alpha-bug
